# Generated by Django 3.2.9 on 2021-11-30 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='begin_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
