# Generated by Django 3.2.9 on 2021-11-30 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20211129_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timestamp',
            name='begin_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
